version: "3.9"

services:
  database:
    image: postgres
    container_name: postgres-container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sozei
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: node-container
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local